#!/bin/sh

CFG=$HOME/.cfg
CVS=$HOME/.cvs
CONF=$CVS/config
CPUB=$CVS/personal/pub/config
CSEC=$CVS/personal/sec/config
TLA=$HOME/.tla
TLAR=$HOME/.tla-relocations
BAZ=$HOME/.baz
BAZR=$HOME/.baz-relocations
